DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS IMAGES;

CREATE TABLE USERS(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
UserName TEXT UNIQUE NOT NULL,
PassWord TEXT NOT NULL,
Email TEXT NOT NULL,
Date TEXT NOT NULL);

CREATE TABLE IMAGES(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
FileName TEXT NOT NULL,
ImageTitle TEXT NOT NULL,
Description TEXT,
Dots INT NOT NULL,
User TEXT NOT NULL,
Date TEXT NOT NULL);