DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS IMAGES;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserName TEXT UNIQUE NOT NULL,
    PassWord TEXT NOT NULL,
    Email TEXT NOT NULL,
    Date TEXT NOT NULL);

CREATE TABLE IMAGES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UUID TEXT NOT NULL,
    FileName TEXT NOT NULL,
    ImageTitle TEXT NOT NULL,
    Description TEXT,
    Dots INTEGER DEFAULT 0,
    User TEXT NOT NULL,
    Date TEXT NOT NULL);

CREATE TABLE COMMENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    postUUID TEXT NOT NULL,
    remarkUUID TEXT NOT NULL,
    User TEXT NOT NULL,
    Comment TEXT NOT NULL,
    ReplyTo TEXT,
    Depth INTEGER DEFAULT 1,
    Date TEXT NOT NULL);