DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS IMAGES;

CREATE TABLE USERS(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
UserName TEXT UNIQUE NOT NULL,
PassWord TEXT NOT NULL,
Email TEXT NOT NULL,
Date TEXT NOT NULL);

CREATE TABLE IMAGES(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
UUID TEXT NOT NULL,
FileName TEXT NOT NULL,
ImageTitle TEXT NOT NULL,
Description TEXT,
Dots INTEGER DEFAULT 0,
User TEXT NOT NULL,
Date TEXT NOT NULL);